import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const ORG_ID = 'cmo1i0x810000uqd8v6dvdxny'; // Ironvine

async function main(): Promise<void> {
  console.log('Seeding Ironvine inventory...');

  const items = await prisma.$transaction([
    // ── Blank Shirts ─────────────────────────────────────────────────────────
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-BLK-S', organizationId: ORG_ID } },
      update: { quantityOnHand: 150 },
      create: {
        sku: 'BLANK-GD64-BLK-S',
        name: 'Gildan 64000 Softstyle Tee — Black / Small',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'S',
        color: 'Black',
        quantityOnHand: 150,
        reorderPoint: 30,
        reorderQuantity: 100,
        costPrice: 3.25,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-BLK-M', organizationId: ORG_ID } },
      update: { quantityOnHand: 200 },
      create: {
        sku: 'BLANK-GD64-BLK-M',
        name: 'Gildan 64000 Softstyle Tee — Black / Medium',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'M',
        color: 'Black',
        quantityOnHand: 200,
        reorderPoint: 50,
        reorderQuantity: 150,
        costPrice: 3.25,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-BLK-L', organizationId: ORG_ID } },
      update: { quantityOnHand: 175 },
      create: {
        sku: 'BLANK-GD64-BLK-L',
        name: 'Gildan 64000 Softstyle Tee — Black / Large',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'L',
        color: 'Black',
        quantityOnHand: 175,
        reorderPoint: 50,
        reorderQuantity: 150,
        costPrice: 3.25,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-BLK-XL', organizationId: ORG_ID } },
      update: { quantityOnHand: 120 },
      create: {
        sku: 'BLANK-GD64-BLK-XL',
        name: 'Gildan 64000 Softstyle Tee — Black / XL',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'XL',
        color: 'Black',
        quantityOnHand: 120,
        reorderPoint: 30,
        reorderQuantity: 100,
        costPrice: 3.50,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-BLK-2XL', organizationId: ORG_ID } },
      update: { quantityOnHand: 80 },
      create: {
        sku: 'BLANK-GD64-BLK-2XL',
        name: 'Gildan 64000 Softstyle Tee — Black / 2XL',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: '2XL',
        color: 'Black',
        quantityOnHand: 80,
        reorderPoint: 20,
        reorderQuantity: 75,
        costPrice: 3.75,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-WHT-M', organizationId: ORG_ID } },
      update: { quantityOnHand: 200 },
      create: {
        sku: 'BLANK-GD64-WHT-M',
        name: 'Gildan 64000 Softstyle Tee — White / Medium',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'M',
        color: 'White',
        quantityOnHand: 200,
        reorderPoint: 50,
        reorderQuantity: 150,
        costPrice: 3.00,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-WHT-L', organizationId: ORG_ID } },
      update: { quantityOnHand: 180 },
      create: {
        sku: 'BLANK-GD64-WHT-L',
        name: 'Gildan 64000 Softstyle Tee — White / Large',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'L',
        color: 'White',
        quantityOnHand: 180,
        reorderPoint: 50,
        reorderQuantity: 150,
        costPrice: 3.00,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-NVY-M', organizationId: ORG_ID } },
      update: { quantityOnHand: 100 },
      create: {
        sku: 'BLANK-GD64-NVY-M',
        name: 'Gildan 64000 Softstyle Tee — Navy / Medium',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'M',
        color: 'Navy',
        quantityOnHand: 100,
        reorderPoint: 25,
        reorderQuantity: 75,
        costPrice: 3.25,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD64-NVY-L', organizationId: ORG_ID } },
      update: { quantityOnHand: 100 },
      create: {
        sku: 'BLANK-GD64-NVY-L',
        name: 'Gildan 64000 Softstyle Tee — Navy / Large',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'L',
        color: 'Navy',
        quantityOnHand: 100,
        reorderPoint: 25,
        reorderQuantity: 75,
        costPrice: 3.25,
        organizationId: ORG_ID,
      },
    }),
    // Bella+Canvas premium tees
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-BC3001-BLK-M', organizationId: ORG_ID } },
      update: { quantityOnHand: 75 },
      create: {
        sku: 'BLANK-BC3001-BLK-M',
        name: 'Bella+Canvas 3001 Unisex Tee — Black / Medium',
        category: 'BLANK_SHIRTS',
        brand: 'Bella+Canvas',
        size: 'M',
        color: 'Black',
        quantityOnHand: 75,
        reorderPoint: 20,
        reorderQuantity: 50,
        costPrice: 6.50,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-BC3001-BLK-L', organizationId: ORG_ID } },
      update: { quantityOnHand: 75 },
      create: {
        sku: 'BLANK-BC3001-BLK-L',
        name: 'Bella+Canvas 3001 Unisex Tee — Black / Large',
        category: 'BLANK_SHIRTS',
        brand: 'Bella+Canvas',
        size: 'L',
        color: 'Black',
        quantityOnHand: 75,
        reorderPoint: 20,
        reorderQuantity: 50,
        costPrice: 6.50,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-BC3001-WHT-M', organizationId: ORG_ID } },
      update: { quantityOnHand: 60 },
      create: {
        sku: 'BLANK-BC3001-WHT-M',
        name: 'Bella+Canvas 3001 Unisex Tee — White / Medium',
        category: 'BLANK_SHIRTS',
        brand: 'Bella+Canvas',
        size: 'M',
        color: 'White',
        quantityOnHand: 60,
        reorderPoint: 15,
        reorderQuantity: 50,
        costPrice: 6.25,
        organizationId: ORG_ID,
      },
    }),
    // Hoodies
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD185-BLK-M', organizationId: ORG_ID } },
      update: { quantityOnHand: 60 },
      create: {
        sku: 'BLANK-GD185-BLK-M',
        name: 'Gildan 18500 Heavy Blend Hoodie — Black / Medium',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'M',
        color: 'Black',
        quantityOnHand: 60,
        reorderPoint: 15,
        reorderQuantity: 50,
        costPrice: 10.50,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD185-BLK-L', organizationId: ORG_ID } },
      update: { quantityOnHand: 60 },
      create: {
        sku: 'BLANK-GD185-BLK-L',
        name: 'Gildan 18500 Heavy Blend Hoodie — Black / Large',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'L',
        color: 'Black',
        quantityOnHand: 60,
        reorderPoint: 15,
        reorderQuantity: 50,
        costPrice: 10.50,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'BLANK-GD185-NVY-L', organizationId: ORG_ID } },
      update: { quantityOnHand: 40 },
      create: {
        sku: 'BLANK-GD185-NVY-L',
        name: 'Gildan 18500 Heavy Blend Hoodie — Navy / Large',
        category: 'BLANK_SHIRTS',
        brand: 'Gildan',
        size: 'L',
        color: 'Navy',
        quantityOnHand: 40,
        reorderPoint: 10,
        reorderQuantity: 40,
        costPrice: 10.50,
        organizationId: ORG_ID,
      },
    }),

    // ── DTF Transfers ─────────────────────────────────────────────────────────
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'DTF-FILM-22IN-100FT', organizationId: ORG_ID } },
      update: { quantityOnHand: 8 },
      create: {
        sku: 'DTF-FILM-22IN-100FT',
        name: 'DTF PET Film Roll — 22" × 100ft',
        category: 'DTF_TRANSFERS',
        quantityOnHand: 8,
        reorderPoint: 2,
        reorderQuantity: 10,
        costPrice: 45.00,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'DTF-POWDER-1KG-WHT', organizationId: ORG_ID } },
      update: { quantityOnHand: 12 },
      create: {
        sku: 'DTF-POWDER-1KG-WHT',
        name: 'DTF Hot Melt Adhesive Powder — White 1kg',
        category: 'DTF_TRANSFERS',
        quantityOnHand: 12,
        reorderPoint: 3,
        reorderQuantity: 10,
        costPrice: 18.00,
        organizationId: ORG_ID,
      },
    }),

    // ── Vinyl ─────────────────────────────────────────────────────────────────
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'HTV-SISER-BLK-15IN', organizationId: ORG_ID } },
      update: { quantityOnHand: 25 },
      create: {
        sku: 'HTV-SISER-BLK-15IN',
        name: 'Siser EasyWeed HTV — Black 15" × 15yd',
        category: 'VINYL',
        brand: 'Siser',
        color: 'Black',
        quantityOnHand: 25,
        reorderPoint: 5,
        reorderQuantity: 20,
        costPrice: 32.00,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'HTV-SISER-WHT-15IN', organizationId: ORG_ID } },
      update: { quantityOnHand: 20 },
      create: {
        sku: 'HTV-SISER-WHT-15IN',
        name: 'Siser EasyWeed HTV — White 15" × 15yd',
        category: 'VINYL',
        brand: 'Siser',
        color: 'White',
        quantityOnHand: 20,
        reorderPoint: 5,
        reorderQuantity: 20,
        costPrice: 32.00,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'HTV-SISER-RED-15IN', organizationId: ORG_ID } },
      update: { quantityOnHand: 10 },
      create: {
        sku: 'HTV-SISER-RED-15IN',
        name: 'Siser EasyWeed HTV — Red 15" × 15yd',
        category: 'VINYL',
        brand: 'Siser',
        color: 'Red',
        quantityOnHand: 10,
        reorderPoint: 3,
        reorderQuantity: 10,
        costPrice: 32.00,
        organizationId: ORG_ID,
      },
    }),

    // ── Packaging ─────────────────────────────────────────────────────────────
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'PKG-POLY-MAILER-SM', organizationId: ORG_ID } },
      update: { quantityOnHand: 500 },
      create: {
        sku: 'PKG-POLY-MAILER-SM',
        name: 'Poly Mailer Bags — 10"×13" (Pack of 100)',
        category: 'PACKAGING',
        quantityOnHand: 500,
        reorderPoint: 100,
        reorderQuantity: 500,
        costPrice: 0.18,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'PKG-TISSUE-WHT', organizationId: ORG_ID } },
      update: { quantityOnHand: 1000 },
      create: {
        sku: 'PKG-TISSUE-WHT',
        name: 'White Tissue Paper Sheets (Pack of 100)',
        category: 'PACKAGING',
        quantityOnHand: 1000,
        reorderPoint: 200,
        reorderQuantity: 500,
        costPrice: 0.05,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'PKG-HANG-TAG-BLK', organizationId: ORG_ID } },
      update: { quantityOnHand: 500 },
      create: {
        sku: 'PKG-HANG-TAG-BLK',
        name: 'Hang Tags — Black Matte (Pack of 100)',
        category: 'PACKAGING',
        quantityOnHand: 500,
        reorderPoint: 100,
        reorderQuantity: 300,
        costPrice: 0.22,
        organizationId: ORG_ID,
      },
    }),

    // ── Ink ───────────────────────────────────────────────────────────────────
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'INK-DTF-BLK-1L', organizationId: ORG_ID } },
      update: { quantityOnHand: 6 },
      create: {
        sku: 'INK-DTF-BLK-1L',
        name: 'DTF Ink Black — 1 Liter',
        category: 'INK',
        color: 'Black',
        quantityOnHand: 6,
        reorderPoint: 2,
        reorderQuantity: 6,
        costPrice: 28.00,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'INK-DTF-WHT-1L', organizationId: ORG_ID } },
      update: { quantityOnHand: 6 },
      create: {
        sku: 'INK-DTF-WHT-1L',
        name: 'DTF Ink White — 1 Liter',
        category: 'INK',
        color: 'White',
        quantityOnHand: 6,
        reorderPoint: 2,
        reorderQuantity: 6,
        costPrice: 30.00,
        organizationId: ORG_ID,
      },
    }),
    prisma.inventoryItem.upsert({
      where: { sku_organizationId: { sku: 'INK-DTF-CMY-1L', organizationId: ORG_ID } },
      update: { quantityOnHand: 4 },
      create: {
        sku: 'INK-DTF-CMY-1L',
        name: 'DTF Ink CMY Set — 1 Liter each',
        category: 'INK',
        quantityOnHand: 4,
        reorderPoint: 1,
        reorderQuantity: 4,
        costPrice: 82.00,
        organizationId: ORG_ID,
      },
    }),
  ]);

  console.log(`✓ Created/updated ${items.length} inventory items`);
  console.log('Seeding complete.');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
